### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by switowski** [switowski/deploystack#1]
Next tools, services that will be described:
- [x] SSL
- [x] uptime monitoring
- [x] files hosting
- [x] Version Control
- [x] CDN
- [x] e-mail campaigns and transactional emails
- [x] CI (continuous integration) and CD (continous delivery) [#8]
- [x] errors tracking
- [ ] users feedback (needs some suggestions for the tools)
- [ ] ~~cpu, memory, I/O monitoring~~(not really so useful, there are plenty articles online on that)
- [x] static websites [#2]
- [ ] browser testing (https://stackshare.io/browserstack and friends)

**Comment by jorgebg** [comment]
Awesome work! I would like to ask, did you consider adding Sentry?

**Comment by sundarv85** [comment]
Nice list. How about real user monitoring along with error tracking. Some tools are:

NewRelic - https://newrelic.com/browser-monitoring/features
Atatus - https://www.atatus.com/browser-monitoring/overview
Raygun - https://raygun.com/products/real-user-monitoring

**Comment by switowski** [comment]
@jorgebg 
> Awesome work! I would like to ask, did you consider adding Sentry?

Thanks for nice words and for the suggestion, I took a note of Sentry and will check it out for the next update.

**Comment by sundarv85** [comment]
thanks @switowski I suppose real user monitoring tools are different from error monitoring. From the popular opinion, I see that Sentry should get into error monitoring while Raygun will fit better in real user monitoring. Just my 2c.

**Comment by switowski** [comment]
Closing, this project will no longer be updated.
